###
GET http://127.0.0.1:3005/api/users/100

###
POST  http://127.0.0.1:3005/api/users
Content-Type: application/json

{
    "user": {
        "email": "nestle@nestle.com",
        "password": "Nestle123",
        "isAdmin": true,
        "createdAt": "hoy"
    }
}

###
DELETE http://127.0.0.1:3005/api/users/a9ea1dcd-4355-4459-9564-3766780cfe13