###
GET http://127.0.0.1:3005/api/users/100

###
POST  http://127.0.0.1:3005/api/users
Content-Type: application/json

{
    "user": {
        "name": "Matías",
        "email": "nestle@nestle.com",
        "password": "Nestle123",
        "role": "Admin"
    }
}

###
DELETE http://127.0.0.1:3005/api/users/4d95395c-7267-4124-811f-ddb1253877ab

###
GET http://127.0.0.1:3005/api/users