###
GET http://127.0.0.1:3005/api/users/100

###
POST  http://127.0.0.1:3005/api/users
Content-Type: application/json

{
    "user": {
        "name": "Matías",
        "email": "nestle@nestle.com",
        "password": "Nestle123",
        "admin": false
    }
}

###
DELETE http://127.0.0.1:3005/api/users/b41d5318-abf3-4517-89a8-5718f6646d29

###
GET http://127.0.0.1:3005/api/users