// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB1cgZJ5p7I6ph7RR03a67Co7I7z1dVR4',
    appId: '1:241241482881:web:0fb820e6e4b468c069cf80',
    messagingSenderId: '241241482881',
    projectId: 'analisis-de-artes',
    authDomain: 'analisis-de-artes.firebaseapp.com',
    storageBucket: 'analisis-de-artes.firebasestorage.app',
    measurementId: 'G-Z92F928R4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0W9pOYvicGn7e4fv6sg-zvyQ-JDjb0sc',
    appId: '1:241241482881:android:0cf8383e5274d15069cf80',
    messagingSenderId: '241241482881',
    projectId: 'analisis-de-artes',
    storageBucket: 'analisis-de-artes.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB1cgZJ5p7I6ph7RR03a67Co7I7z1dVR4',
    appId: '1:241241482881:web:440ce51a76570b0869cf80',
    messagingSenderId: '241241482881',
    projectId: 'analisis-de-artes',
    authDomain: 'analisis-de-artes.firebaseapp.com',
    storageBucket: 'analisis-de-artes.firebasestorage.app',
    measurementId: 'G-PLB7BV0EES',
  );
}
